spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: ${CERT_PUBLICKEY:file:/tmp/authPublicKey.pem}
  sleuth:
    sampler:
      probability: 1
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
server:
  port: ${SERVER_PORT:0}

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: prod

  sleuth:
    sampler:
      probability: 0.1

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
