server:
  port: ${SERVER_PORT:0}

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: prod

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
