zuul:
  ignoredServices: '*'
  routes:
    auth-service:
      path: /oauth/**
      serviceId: auth-service
      stripPrefix: false
      sensitiveHeaders:
    person-service:
      path: /api/people/**
      serviceId: person-service
      stripPrefix: false
      sensitiveHeaders:
    todo-service:
      path: /api/todos/**
      serviceId: todo-service
      stripPrefix: false
      sensitiveHeaders: