apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todo-service
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - match:
        - uri:
            prefix: /api/todos
      route:
        - destination:
            host: todo-service
            port:
              number: 8081
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-person-service
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - match:
        - uri:
            prefix: /api/people
      route:
        - destination:
            host: istio-person-service
            port:
              number: 8081
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-oauth-service
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - match:
        - uri:
            prefix: /oauth
        - uri:
            prefix: /.well-known/jwks.json
      route:
        - destination:
            host: istio-oauth-service
            port:
              number: 9999
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-person-or-todo-service
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - match:
        - uri:
            exact: /api/people-or-todos
        - headers:
            user-preference:
              exact: "people"
      rewrite:
        uri: /api/people
      route:
        - destination:
            host: istio-person-service
            port:
              number: 8081
    - match:
        - uri:
            exact: /api/people-or-todos
        - headers:
            user-preference:
              exact: "todo"
      rewrite:
        uri: /api/todos
      route:
        - destination:
            host: todo-service
            port:
              number: 8081
