apiVersion: v1
kind: Service
metadata:
  name: todo-service
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: todo-service
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 8081
  selector:
    app: todo-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
spec:
  selector:
    matchLabels:
      app: todo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-service
        version: v1
    spec:
      containers:
        - name: todo-service
          image: todo-service:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: privatekey
              mountPath: "/etc/private_key"
              readOnly: true
            - name: publickey
              mountPath: "/etc/public_key"
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: QUARKUS_HTTP_PORT
              value: "8081"
            - name: QUARKUS_PROFILES
              value: prod
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
            - name: MONGODB_DATABASE
              value: docker
            - name: PUBLIC_KEY_PATH
              value: /etc/public_key/dummyAuthPublicKey.pem
            - name: QUARKUS_METRICS_PATH
              value: /actuator
            - name: LOG_LEVEL_JWT
              value: DEBUG
            - name: PERSON_API_URL
              value: http://istio-person-service.default.svc.cluster.local:8081/api/people
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8081
            initialDelaySeconds: 200
            periodSeconds: 5
      volumes:
        - name: publickey
          secret:
            secretName: publickey
        - name: privatekey
          secret:
            secretName: privatekey
