apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-oauth-service
  labels:
    app: rbac-role
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "apps"
    resources:
      - services
      - pods
      - endpoints
      - namespaces
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-oauth-service
  labels:
    app: rbac-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-oauth-service
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "request-authentication-jwt-person-service"
  namespace: default
  labels:
    app: request-authentication-jwt-person-service
spec:
  selector:
    matchLabels:
      app: istio-person-service
  jwtRules:
    - issuer: "admin"
      jwksUri: "http://istio-oauth-service.default.svc.cluster.local:9999/.well-known/jwks.json"
---
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "authorization-policy-person-service"
  namespace: default
  labels:
    app: authorization-policy-person-service
spec:
  selector:
    matchLabels:
      app: istio-person-service
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
#---
#apiVersion: "security.istio.io/v1beta1"
#kind: "AuthorizationPolicy"
#metadata:
#  name: "allow-jwks-ingress"
#  namespace: istio-system
#spec:
#  selector:
#    matchLabels:
#      istio: ingressgateway
#  action: ALLOW
#  rules:
#    - to:
#        - operation:
#            paths: ["/.well-known/jwks.json"]
#---
#kind: ClusterRoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: kubelet-api-admin
#subjects:
#  - kind: User
#    name: kube-apiserver-kubelet-client
#    apiGroup: rbac.authorization.k8s.io
#roleRef:
#  kind: ClusterRole
#  name: system:kubelet-api-admin
#  apiGroup: rbac.authorization.k8s.io